version: "3.8"

services:
  onlinemenu_nestjs_test:
    container_name: onlinemenu_nestjs_test
    build:
        # context mean where to find the Dockerfile
        context: ./
        # target mean the target to build
        target: dev
    image: thelittlesheep/onlinemenu_nestjs:dev
    command: yarn test
    restart: "no"
  # onlinemenu_nestjs:
  #   container_name: onlinemenu_nestjs
  #   image: thelittlesheep/onlinemenu_nestjs:dev
  #   command: yarn start:debug
  #   ports:
  #       - 3000:3000
  #       - 9229:9229
  #   volumes:
  #       - .:/usr/src/app
  #   restart: unless-stopped
  # onlinemenu_redis:
  #   container_name: onlinemenu_redis
  #   image: redis:alpine
  #   ports:
  #     - 6379:6379
  #   restart: unless-stopped