version: "3.9"

services:
  onlinemenu_nestjs:
    container_name: onlinemenu_nestjs
    image: thelittlesheep/onlinemenu_nestjs:dev
    command: yarn start:debug
    ports:
        - 3000:3000
        - 9229:9229
    volumes:
        - .:/usr/src/app
    restart: unless-stopped
  onlinemenu_redis:
    container_name: onlinemenu_redis
    image: redis:alpine
    ports:
      - 6379:6379
    restart: unless-stopped

networks:
  default:
    external: true
    name: web_service