name: Docker Image CI_CD

on:
  push:
    branches: [ "CI_CD" ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:


  build:

    runs-on: ubuntu-latest
    - uses: actions/checkout@v3
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test

    steps:
    - uses: actions/checkout@v3
    - name: Build the base Docker image
      run: docker build . --file Dockerfile --target base --tag thelittlesheep/onlinemenu:base
    - name: Build the dev Docker image
      run: docker build . --file Dockerfile --target dev --tag thelittlesheep/onlinemenu:dev