name: Docker Image CI_CD

on:
  push:
    branches: [ "CI_CD" ]

jobs:

  test:

    name: Jest test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test

  build docker image:

    name: build docker image and push to Docker Hub

    needs: test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the base Docker image
      run: docker build . --file Dockerfile --target base --tag thelittlesheep/onlinemenu:base
    - name: Build the dev Docker image
      run: docker build . --file Dockerfile --target dev --tag thelittlesheep/onlinemenu:dev